### ISSUE TITLE
[API/UI] Implement Compound CSS Refactor

### ISSUE THREAD

**Issue by jaren0401** [jaren0401/css-refactor-fyp#26]
Example:
```css
   .box {
        width: 40px;
        height: 40px;
        background-color: red;
    }

    .background-blue {
        background-color: blue;
    }
```
should become

```css
    .box {
        width: 40px;
        height: 40px;
    }

    .background-red {
        background-color: red;
    }

    .background-blue {
        background-color: blue;
    }
```

- [x] Dev - Implement tree manipulation of the nodes
- [x] Dev - Send back manipulated tree to be displayed in front end
